Reduce uggs
nickcolley/itsyourbirthdaytoday pull request #15
Opened 2018-05-10 23:50 UTC by zaccolley

Remove label visually
Only have underline for input not a box

Would close #14

2018-05-10 23:57 UTC, nickcolley commented on styles.css
>  label {
would rathre use aria-label than do this

2018-05-11 08:51 UTC, NickColley requested changes
hiding the label is flakier than using aria-label

2018-05-13 22:30 UTC, zaccolley commented
Don't know what this means, can you explain more?

2018-05-13 23:39 UTC, nickcolley commented
aria-label has pretty good support and doesnt rely on CSS hacks

2018-05-14 09:10 UTC, zaccolley commented
yeah i still dont know what that means though?

2019-02-01 11:54 UTC, closed without merging